language: python
python:
  - '3.6'

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run --rm cuenca_app sh -c "python ./tests/test_n_queen.py && python ./tests/test_n_queen_model.py && flake8 --ignore=E501,E402"
